#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#polybar
$HOME/polybar-collection/launch.sh

#wallpaper
feh --bg-fill ~/Pictures/gw.jpg

#backlight
xbacklight -set 5.0

#conky
#conky

#picom
picom --blur-method box --experimental-backends 

#wifi
nm-applet &

#usb-mount
udiskie &

#pywal
wal -i ~/Pictures/gw.jpg

#tap to click
synclient TapButton1=1

xsetroot -cursor_name left_ptr 
